const state=JSON.parse(localStorage.getItem('docenteDigitalPrototype')||'{}');
state.mode=state.mode||'easy';state.level=state.level||'';state.ieType=state.ieType||'';state.grades=state.grades||[];state.areas=state.areas||[];state.language=state.language||'Castellano';state.quechuaVar=state.quechuaVar||'Quechua Collao';
const save=()=>localStorage.setItem('docenteDigitalPrototype',JSON.stringify(state));
function setMode(mode){state.mode=mode;save();document.body.classList.toggle('expert',mode==='expert');document.getElementById('easyBtn').classList.toggle('active',mode==='easy');document.getElementById('expertBtn').classList.toggle('active',mode==='expert');syncTitle()}
function go(id){if(!state.level&&id!=='setup'){showSetup();return}document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));refresh();window.scrollTo({top:0,behavior:'smooth'})}
function showSetup(){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('setup').classList.add('active')}
function chooseOne(key,val,btn){state[key]=val;btn.parentElement.querySelectorAll('.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}
function nextSetup(n){if(n===2&&!state.level)return alert('Primero selecciona el nivel educativo.');if(n===3&&!state.ieType)return alert('Selecciona el tipo de IE.');if(n===4&&!state.grades.length)return alert('Selecciona al menos un grado o edad.');[1,2,3,4].forEach(i=>document.getElementById('step'+i).classList.toggle('hidden',i!==n));[1,2,3,4].forEach(i=>document.getElementById('s'+i).classList.toggle('active',i<=n));if(n===3)renderGrades();if(n===4)renderAreas()}
function gradeOptions(){if(state.level==='Inicial')return['3 años','4 años','5 años'];if(state.level==='Primaria')return['1.º','2.º','3.º','4.º','5.º','6.º'];return['1.º','2.º','3.º','4.º','5.º']}
function areaOptions(){if(state.level==='Inicial')return['Comunicación','Matemática','Personal Social','Ciencia y Tecnología','Psicomotriz','Arte y Cultura'];if(state.level==='Primaria')return['Comunicación','Matemática','Personal Social','Ciencia y Tecnología','Arte y Cultura','Educación Física','Educación Religiosa'];return['Comunicación','Matemática','Ciencia y Tecnología','Ciencias Sociales','DPCC','Inglés','Educación Física','Arte y Cultura','Educación Religiosa','EPT']}
function renderGrades(){const wrap=document.getElementById('gradeChoices');wrap.innerHTML='';const multi=state.ieType==='Multigrado'||state.ieType==='Unidocente';document.getElementById('gradeHelp').textContent=multi?'Puedes seleccionar varios grados o edades para una planificación común y diferenciada.':'Selecciona el grado con el que trabajarás.';gradeOptions().forEach(g=>{const b=document.createElement('button');b.className='choice'+(state.grades.includes(g)?' active':'');b.textContent=g;b.onclick=()=>{if(multi){state.grades=state.grades.includes(g)?state.grades.filter(x=>x!==g):[...state.grades,g]}else state.grades=[g];renderGrades()};wrap.appendChild(b)})}
function renderAreas(){const wrap=document.getElementById('areaChoices');wrap.innerHTML='';const multiple=state.level!=='Secundaria';document.getElementById('areaHelp').textContent=multiple?'En Inicial y Primaria puedes seleccionar varias áreas.':'En Secundaria la programación se organiza por área.';areaOptions().forEach(a=>{const b=document.createElement('button');b.className='choice'+(state.areas.includes(a)?' active':'');b.textContent=a;b.onclick=()=>{if(multiple){state.areas=state.areas.includes(a)?state.areas.filter(x=>x!==a):[...state.areas,a]}else state.areas=[a];renderAreas()};wrap.appendChild(b)})}
function finishSetup(){if(!state.areas.length)return alert('Selecciona al menos un área.');state.language=document.getElementById('language').value;state.quechuaVar=document.getElementById('quechuaVar').value;save();fillSelects();go('home')}
function fillSelects(){const grades=state.grades.length?state.grades:gradeOptions();const areas=state.areas.length?state.areas:areaOptions();document.getElementById('materialGrade').innerHTML=grades.map(x=>`<option>${x}</option>`).join('');document.getElementById('diagnosticArea').innerHTML=areas.map(x=>`<option>${x}</option>`).join('')}
function contextText(){return`${state.level} · ${state.ieType} · ${state.grades.join(', ')} · ${state.areas.join(', ')}`}
function refresh(){if(!state.level)return;fillSelects();const text=contextText();document.getElementById('homeContext').textContent=text;document.getElementById('sessionContext').innerHTML=`<b>Contexto cargado:</b> ${text}<br>La app no vuelve a pedir estos datos.`;document.getElementById('settingsSummary').innerHTML=`<b>Nivel:</b> ${state.level}<br><b>Tipo de IE:</b> ${state.ieType}<br><b>Grados/edades:</b> ${state.grades.join(', ')}<br><b>Áreas:</b> ${state.areas.join(', ')}<br><b>Idioma:</b> ${state.language}${state.language!=='Castellano'?' · '+state.quechuaVar:''}`}
function showDiagnostic(){document.getElementById('diagnosticPanel').classList.remove('hidden');fillSelects();document.getElementById('diagnosticPanel').scrollIntoView({behavior:'smooth'})}
function generateDiagnostic(){document.getElementById('diagnosticResult').classList.remove('hidden')}
function demoAnnual(){alert('Prototipo: la programación anual usará diagnóstico, contexto, calendario, recursos y CNEB para proponer una planificación editable.')}
function showUnit(){if(!state.level||!state.ieType||!state.grades.length||!state.areas.length){alert('Primero completa Nivel + Tipo de IE + Grados/Áreas.');return restartSetup()}document.getElementById('unitContext').innerHTML=`✓ <b>${state.level}</b> · <b>${state.ieType}</b> · Grados/edades: <b>${state.grades.join(', ')}</b> · Áreas: <b>${state.areas.join(', ')}</b>`;document.getElementById('unitPanel').classList.remove('hidden');document.getElementById('unitPanel').scrollIntoView({behavior:'smooth'})}
function createUnitDemo(){document.getElementById('unitReady').classList.remove('hidden')}
function syncTitle(){const title=document.getElementById('sessionTitle');if(!title)return;title.value=document.getElementById('activity').value;title.readOnly=state.mode==='easy'}
function generateSession(){syncTitle();document.getElementById('docTitle').textContent=document.getElementById('sessionTitle').value.toUpperCase();document.getElementById('sessionOutput').classList.remove('hidden');document.getElementById('sessionOutput').scrollIntoView({behavior:'smooth'})}
function sendCorrection(){const input=document.getElementById('chatInput');const t=input.value.trim();if(!t)return;const d=document.createElement('div');d.className='chatmsg';d.innerHTML=`💬 <b>Tu indicación:</b> ${t}<br><span>Prototipo: se conservaría lo aprobado y se modificaría únicamente lo solicitado.</span>`;document.getElementById('chatLog').prepend(d);input.value=''}
function generateMaterial(){const lang=document.getElementById('materialLanguage').value;const variety=document.getElementById('materialQuechua').value;let text='';if(lang==='Castellano')text='En nuestra comunidad cuidamos el agua porque sostiene la vida de las personas, animales y plantas. Reutilizarla responsablemente ayuda a proteger nuestro entorno.';else if(lang==='Quechua')text=`[Demostración ${variety}] Kay yakuqa kawsayninchikpaq ancha chaninniyuqmi. Yaku waqaychayqa ayllunchikta yanapan.`;else text=`CASTELLANO: Cuidamos el agua y evitamos desperdiciarla. | ${variety}: Kay yakuqa kawsayninchikpaq ancha chaninniyuqmi.`;document.getElementById('materialText').textContent=text;document.getElementById('materialOutput').classList.remove('hidden')}
function showEvaluation(kind){const p=document.getElementById('evaluationPanel');p.classList.remove('hidden');if(kind==='register'){p.innerHTML=`<h2>📋 Registro de evaluación</h2><p>Usa criterios y evidencias ya registrados.</p><label>Nivel de logro<select><option>AD</option><option>A</option><option selected>B</option><option>C</option></select></label>`}else if(kind==='unit'){p.innerHTML=`<h2>🧪 Evaluación de unidad/proyecto</h2><div class="form2"><label>Idioma<select><option>Castellano</option><option>Quechua</option><option>Bilingüe</option></select></label><label>Tipo<select><option>Mixta</option><option>Escrita</option><option>Oral</option><option>Producto/desempeño</option></select></label></div><div class="notice">Cambiar el idioma no cambia el criterio ni la dificultad.</div><button class="btn">✨ Crear evaluación</button>`}else{p.innerHTML=`<h2>📝 Conclusiones descriptivas SIAGIE</h2><div class="document"><p><b>Competencia:</b> Resuelve problemas de cantidad</p><p><b>Nivel:</b> B</p><p><b>Conclusión propuesta:</b> Resuelve situaciones empleando estrategias de cálculo y explica parte de sus procedimientos. Requiere fortalecer la justificación de sus respuestas en situaciones nuevas.</p></div><p><button class="btn">✓ Aprobar</button> <button class="btn alt">✏️ Corregir</button> <button class="btn ghost">📋 Copiar para SIAGIE</button></p>`}p.scrollIntoView({behavior:'smooth'})}
function restartSetup(){showSetup();nextSetup(1)}
function resetDemo(){if(confirm('¿Restablecer la configuración del prototipo?')){localStorage.removeItem('docenteDigitalPrototype');location.reload()}}
setMode(state.mode);syncTitle();if(state.level){fillSelects();go('home')}else showSetup();