let activeRecognition=null;
let speechRunId=0;

function readingCard(r){const p=state.progress[r.code]||{};return `<article class="reading-card ${p.completed?'done':''}" data-code="${r.code}"><div class="icon">${r.emoji}</div><div><span class="eyebrow">LECTURA ${r.code}</span><h3>${escapeHtml(r.title)}</h3><p>${r.word_count||r.body_text.split(/\s+/).length} palabras · ${r.words.length} palabras focales</p></div><div class="status-dot">${p.completed?'✓':'›'}</div></article>`}
function renderHome(){ $('#readingGrid').innerHTML=state.readings.map(readingCard).join('');document.querySelectorAll('.reading-card').forEach(c=>c.onclick=()=>openReading(c.dataset.code));const done=Object.values(state.progress).filter(p=>p.completed).length;$('#doneCount').textContent=done;$('#globalBar').style.width=`${Math.round(done/Math.max(1,state.readings.length)*100)}%`;const pending=state.events.some(e=>!e.synced);$('#syncLabel').textContent=navigator.onLine?(pending?'Hay avances pendientes de sincronizar':state.binding?.student_id?'Sincronización disponible':'Guardado local · falta vincular este dispositivo'):'Guardado en este dispositivo · sin Internet';}
function showView(id){['studentHome','readerView','teacherView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));}
function openReading(code){stopSpeech();stopDictation();state.current=state.readings.find(r=>r.code===code);state.step=state.progress[code]?.lastStep||0;state.answers={};$('#readingCode').textContent='LECTURA '+code;$('#readingTitle').textContent=state.current.title;$('#readingEmoji').textContent=state.current.emoji;showView('readerView');renderReader();}
function renderStepper(){ $('#stepper').innerHTML=steps.map((s,i)=>`<div class="step ${i===state.step?'active':i<state.step?'done':''}">${i+1}. ${s}</div>`).join(''); }
function wordText(w){return typeof w==='string'?w:(w.word||'')}
function wordEmoji(w){return w.emoji||emojiForWord(wordText(w))}
function highlightText(text,words){let out=escapeHtml(text);words.forEach(w=>{const x=wordText(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(`\\b(${x}s?)\\b`,'gi'),'<mark>$1</mark>')});return out}
function makeFindable(r){let text=escapeHtml(r.body_text);r.words.forEach(w=>{const x=wordText(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');text=text.replace(new RegExp(`\\b(${x}s?)\\b`,'gi'),m=>`<span class="find-word" data-word="${escapeHtml(wordText(w))}">${m}</span>`)});return text}
function sentenceParts(text){return String(text||'').trim().split(/(?<=[.!?])\s+/).filter(Boolean)}
function guidedTextHtml(r){return sentenceParts(r.body_text).map((s,i)=>`<span class="sentence" data-sentence="${i}">${highlightText(s,r.words)}</span>`).join(' ')}
function questionHtml(q,i){
  const options=Array.isArray(q.options)&&q.options.length?q.options:null;
  const listen=`<button class="listen-q voice-btn" data-q="${i}">🔊 Escuchar pregunta</button>`;
  if(options)return `<div class="question" data-q="${i}" data-answer="${escapeHtml(q.answer)}"><div class="question-top"><span class="eyebrow">${escapeHtml(q.level).toUpperCase()}</span>${listen}</div><h3>${escapeHtml(q.prompt)}</h3><div class="options">${options.map(o=>`<button class="option" data-value="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="feedback"></div></div>`;
  return `<div class="question" data-q="${i}"><div class="question-top"><span class="eyebrow">${escapeHtml(q.level).toUpperCase()}</span>${listen}</div><h3>${escapeHtml(q.prompt)}</h3><textarea id="openQ${i}" class="big-input oral-answer" placeholder="Puedes hablar o escribir tu respuesta..."></textarea><div class="audio-row"><button class="primary mic-open mic-action" data-q="${i}">🎙️ Responder hablando</button><button class="secondary save-open" data-q="${i}">Guardar</button></div><div class="feedback"></div></div>`;
}
function guideCard(text,emoji='🦙'){return `<div class="voice-guide"><div class="guide-avatar">${emoji}</div><div><b>Kusi te acompaña</b><p>${escapeHtml(text)}</p></div></div>`}
function renderReader(){
  stopSpeech();stopDictation();
  const r=state.current;renderStepper();$('#prevBtn').disabled=state.step===0;$('#nextBtn').textContent=state.step===steps.length-1?'Terminar':'Continuar';const stage=$('#stage');
  if(state.step===0){stage.innerHTML=`${guideCard('Mira la imagen. Primero escucha la pregunta y luego cuéntame qué crees que pasará.')}<div class="prediction-scene"><div class="visual-box">${r.emoji}<br><small>🤔</small></div><div><h2 class="stage-title">Antes de leer</h2><p class="stage-lead prediction-prompt">${escapeHtml(r.prediction)}</p><div class="audio-row voice-actions"><button id="listenPrediction" class="voice-btn primary">🔊 Escuchar consigna</button><button id="predictionMic" class="mic-action secondary">🎙️ Responder hablando</button></div><textarea id="predictionInput" class="big-input oral-answer" placeholder="Tu respuesta aparecerá aquí...">${escapeHtml(state.progress[r.code]?.prediction||'')}</textarea><div class="audio-row"><button id="savePrediction" class="primary">Guardar mi predicción</button></div></div></div>`;
    $('#listenPrediction').onclick=()=>speak(`Antes de leer. ${r.prediction}`);
    $('#predictionMic').onclick=()=>startDictation('#predictionInput',{button:$('#predictionMic'),label:'Responder hablando'});
    $('#savePrediction').onclick=async()=>{const v=$('#predictionInput').value.trim();if(!v){toast('Primero cuéntame tu idea con el micrófono o escríbela.');return;}state.progress[r.code]={...(state.progress[r.code]||{}),prediction:v};await saveProgress();await logEvent('prediction_saved','prediction',{text:v,mode:'voice_or_text'});toast('¡Muy bien! Guardé tu predicción.');};
  }
  if(state.step===1){stage.innerHTML=`${guideCard('Primero puedo leer para ti. Luego toca el micrófono y lee tú. No importa si te equivocas: puedes intentarlo otra vez.','🦙📖')}<h2 class="stage-title">Leemos juntos</h2><div class="reading-scene"><div class="visual-box">${r.emoji}<br>🏔️</div><div><div id="guidedReadingText" class="reading-text guided-reading">${guidedTextHtml(r)}</div><div class="read-along-bar"><button id="speakBtn" class="primary">🔊 Kusi lee</button><button id="studentReadBtn" class="mic-action secondary">🎙️ Ahora leo yo</button><button id="stopAll" class="secondary">⏹ Detener</button></div><div id="readingSpeechResult" class="speech-result" hidden></div></div></div>`;
    $('#speakBtn').onclick=async()=>{speakGuidedReading(r.body_text);await logEvent('audio_played','reading_audio',{source:'speechSynthesis',mode:'guided_sentences'});};
    $('#studentReadBtn').onclick=()=>startStudentReading(r);
    $('#stopAll').onclick=()=>{stopSpeech();stopDictation();toast('Lectura detenida');};
  }
  if(state.step===2){stage.innerHTML=`${guideCard('Toca cada palabra para escucharla. Después búscala dentro del texto.')}<h2 class="stage-title">Trabajamos palabras</h2><p class="stage-lead">Mira, escucha y di cada palabra.</p><div class="word-grid">${r.words.map(w=>`<button class="word-card word-practice" data-word="${escapeHtml(wordText(w))}"><div class="emoji">${wordEmoji(w)}</div><b>${escapeHtml(wordText(w))}</b><small>🔊 Toca para escuchar</small><div class="case-pair"><span class="case-chip">${escapeHtml((w.display_upper||wordText(w).toUpperCase()))}</span><span>↔</span><span class="case-chip">${escapeHtml((w.display_lower||wordText(w).toLowerCase()))}</span></div></button>`).join('')}</div><h3>Encuéntralas en el texto</h3><div class="reading-text find-text">${makeFindable(r)}</div><p id="findFeedback" class="feedback">Encontradas: 0/${r.words.length}</p>`;let found=new Set();document.querySelectorAll('.word-practice').forEach(el=>el.onclick=async()=>{const w=el.dataset.word;speak(w);el.classList.add('found');const wordObj=r.words.find(x=>wordText(x)===w);await logEvent('word_image_matched',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null});await logEvent('case_pair_matched',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null})});document.querySelectorAll('.find-word').forEach(el=>el.onclick=async()=>{const w=el.dataset.word;el.classList.add('found');if(!found.has(w)){found.add(w);const wordObj=r.words.find(x=>wordText(x)===w);await logEvent('word_found_in_text',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null});$('#findFeedback').textContent=`Encontradas: ${found.size}/${r.words.length}`;if(found.size===r.words.length){speak('¡Muy bien! Encontraste todas las palabras.');toast('¡Encontraste todas las palabras!')}}});}
  if(state.step===3){stage.innerHTML=`${guideCard('Yo puedo leer cada pregunta. Tú puedes responder hablando o tocando una opción.')}<h2 class="stage-title">Comprendemos</h2><p class="stage-lead">Escucha, piensa y responde. Puedes volver al texto cuando quieras.</p><details><summary>📖 Volver al texto</summary><div class="reading-text">${highlightText(r.body_text,r.words)}</div></details><div id="questions">${r.questions.map((q,i)=>questionHtml(q,i)).join('')}</div>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectOption(b));document.querySelectorAll('.save-open').forEach(b=>b.onclick=()=>saveOpenAnswer(+b.dataset.q));document.querySelectorAll('.mic-open').forEach(b=>b.onclick=()=>startDictation(`#openQ${b.dataset.q}`,{button:b,label:'Responder hablando'}));document.querySelectorAll('.listen-q').forEach(b=>b.onclick=()=>{const q=r.questions[+b.dataset.q];speak(q.prompt)});}
  if(state.step===4){stage.innerHTML=`${guideCard('Ahora relaciona la lectura con tu vida. Si todavía no escribes mucho, puedes responder hablando.')}<div class="transfer-scene"><div class="visual-box">🏠 ↔ ${r.emoji}</div><div class="transfer-box"><h2 class="stage-title">Lo llevo a mi vida</h2><p class="stage-lead">${escapeHtml(r.transfer)}</p><div class="audio-row"><button id="listenTransfer" class="voice-btn primary">🔊 Escuchar</button><button id="micBtn" class="mic-action secondary">🎙️ Responder hablando</button></div><textarea id="transferInput" class="big-input oral-answer" placeholder="Tu respuesta aparecerá aquí...">${escapeHtml(state.progress[r.code]?.transfer||'')}</textarea><div class="audio-row"><button id="transferSave" class="primary">Guardar respuesta</button></div></div></div>`;$('#listenTransfer').onclick=()=>speak(r.transfer);$('#transferSave').onclick=async()=>{const v=$('#transferInput').value.trim();if(!v){toast('Primero responde hablando o escribe una idea.');return;}state.progress[r.code]={...(state.progress[r.code]||{}),transfer:v};await saveProgress();await logEvent('transfer_answered','transfer',{text:v,mode:'voice_or_text'});toast('¡Muy bien! Respuesta guardada')};$('#micBtn').onclick=()=>startDictation('#transferInput',{button:$('#micBtn'),label:'Responder hablando'});}
  if(state.step===5){stage.innerHTML=`${guideCard('Una segunda lectura ayuda mucho. Puedes escucharme una vez y luego leer tú.')}<div class="celebrate"><div class="big">📖✨</div><h2>¡Leemos otra vez!</h2><p class="stage-lead">Busca las palabras que ya conoces.</p><div class="reading-text guided-reading">${guidedTextHtml(r)}</div><div class="audio-row reread-actions"><button id="rereadBtn" class="primary">🔄 Registrar relectura</button><button id="listenAgain" class="secondary">🔊 Kusi lee</button><button id="readAgainMic" class="mic-action secondary">🎙️ Leo yo</button></div></div>`;$('#rereadBtn').onclick=async()=>{state.progress[r.code]={...(state.progress[r.code]||{}),rereads:(state.progress[r.code]?.rereads||0)+1};await saveProgress();await logEvent('reread_started','reread',{count:state.progress[r.code].rereads});toast('Relectura registrada')};$('#listenAgain').onclick=()=>speakGuidedReading(r.body_text);$('#readAgainMic').onclick=()=>startStudentReading(r);}
  $('#prevBtn').onclick=()=>{if(state.step>0){state.step--;renderReader()}};$('#nextBtn').onclick=nextStep;
}
async function selectOption(btn){const wrap=btn.closest('.question');if(wrap.dataset.locked)return;wrap.dataset.locked='1';wrap.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const good=btn.dataset.value===wrap.dataset.answer;btn.classList.add(good?'correct':'incorrect');if(!good){[...wrap.querySelectorAll('.option')].find(x=>x.dataset.value===wrap.dataset.answer)?.classList.add('correct')}wrap.querySelector('.feedback').textContent=good?'✓ ¡Muy bien!':'Vamos a mirar otra vez el texto.';speak(good?'¡Muy bien!':'Vamos a mirar otra vez el texto.');const i=+wrap.dataset.q;state.answers[i]=btn.dataset.value;const q=state.current.questions[i];await logEvent('question_answered',`question:${q.id||i+1}`,{question_id:q.id||null,question_prompt:q.prompt,level:q.level,answer:btn.dataset.value,correct:good,open:false});}
async function saveOpenAnswer(i){const v=$(`#openQ${i}`).value.trim();const q=state.current.questions[i];if(!v){toast('Primero responde hablando o escribe una idea.');return;}state.answers[i]=v;await logEvent('question_answered',`question:${q.id||i+1}`,{question_id:q.id||null,question_prompt:q.prompt,level:q.level,answer:v,open:true,teacher_review:true,mode:'voice_or_text'});document.querySelector(`.question[data-q="${i}"] .feedback`).textContent='✓ Guardé tu respuesta para que la revise el docente.';speak('Muy bien. Guardé tu respuesta.');toast('Respuesta guardada');}
async function nextStep(){stopSpeech();stopDictation();const r=state.current;if(state.step<steps.length-1){state.step++;state.progress[r.code]={...(state.progress[r.code]||{}),lastStep:state.step};await saveProgress();renderReader();window.scrollTo({top:0,behavior:'smooth'});}else{state.progress[r.code]={...(state.progress[r.code]||{}),completed:true,completedAt:new Date().toISOString(),lastStep:5};await saveProgress();await logEvent('reading_completed','reading_complete',{reading_code:r.code});renderHome();showView('studentHome');speak('¡Felicitaciones! Terminaste la lectura.');toast('¡Lectura completada!');}}
function preferredVoice(){const voices=speechSynthesis.getVoices?.()||[];return voices.find(v=>/^es-PE$/i.test(v.lang))||voices.find(v=>/^es-(419|MX|CO|AR|ES)$/i.test(v.lang))||voices.find(v=>/^es/i.test(v.lang))||null}
function stopSpeech(){speechRunId++;if('speechSynthesis' in window)speechSynthesis.cancel();document.querySelectorAll('.sentence.active').forEach(x=>x.classList.remove('active'));}
function speak(text){if(!('speechSynthesis' in window)){toast('Este navegador no puede leer en voz alta.');return;}stopSpeech();const u=new SpeechSynthesisUtterance(String(text||''));u.lang='es-PE';u.rate=.76;u.pitch=1.02;const v=preferredVoice();if(v)u.voice=v;speechSynthesis.speak(u);}
function speakGuidedReading(text){if(!('speechSynthesis' in window)){toast('Este navegador no puede leer en voz alta.');return;}stopSpeech();const run=++speechRunId;const parts=sentenceParts(text);let i=0;const next=()=>{if(run!==speechRunId||i>=parts.length){document.querySelectorAll('.sentence.active').forEach(x=>x.classList.remove('active'));return;}document.querySelectorAll('.sentence.active').forEach(x=>x.classList.remove('active'));document.querySelector(`.sentence[data-sentence="${i}"]`)?.classList.add('active');const u=new SpeechSynthesisUtterance(parts[i]);u.lang='es-PE';u.rate=.72;u.pitch=1.02;const v=preferredVoice();if(v)u.voice=v;u.onend=()=>{i++;next()};u.onerror=()=>{i++;next()};speechSynthesis.speak(u);};next();}
async function ensureMicrophonePermission(){if(!window.isSecureContext){toast('El micrófono necesita una conexión segura HTTPS.');return false;}if(!navigator.mediaDevices?.getUserMedia)return true;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});stream.getTracks().forEach(t=>t.stop());return true;}catch(e){console.warn('mic permission',e);toast('Activa el permiso de micrófono para este sitio en tu navegador.');return false;}}
function recognitionCtor(){return window.SpeechRecognition||window.webkitSpeechRecognition||null}
function stopDictation(){if(activeRecognition){try{activeRecognition.stop()}catch{}activeRecognition=null;}document.querySelectorAll('.mic-action.listening').forEach(b=>{b.classList.remove('listening');if(b.dataset.idleLabel)b.textContent=b.dataset.idleLabel});}
async function startDictation(selector,opts={}){stopSpeech();stopDictation();const SR=recognitionCtor();if(!SR){toast('Este navegador no permite convertir voz a texto. Prueba Chrome en Android o Safari actualizado.');return;}if(!(await ensureMicrophonePermission()))return;const el=$(selector);if(!el)return;const button=opts.button||null;if(button){button.dataset.idleLabel=button.textContent;button.textContent='🎙️ Escuchando…';button.classList.add('listening')}const rec=new SR();activeRecognition=rec;rec.lang='es-PE';rec.interimResults=true;rec.continuous=Boolean(opts.continuous);rec.maxAlternatives=1;let finalText=opts.append?String(el.value||'').trim():'';rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0]?.transcript||'';if(e.results[i].isFinal)finalText=(finalText+' '+t).trim();else interim+=t;}el.value=(finalText+' '+interim).trim();el.dispatchEvent(new Event('input',{bubbles:true}));};rec.onerror=e=>{console.warn('speech recognition',e.error);const msg=e.error==='not-allowed'?'El navegador bloqueó el micrófono. Revisa los permisos.':e.error==='no-speech'?'No escuché tu voz. Acércate al micrófono e inténtalo otra vez.':'No pude reconocer la voz. Inténtalo otra vez.';toast(msg);};rec.onend=()=>{if(button){button.classList.remove('listening');button.textContent=button.dataset.idleLabel||opts.label||'🎙️ Hablar'}activeRecognition=null;if(el.value.trim())toast('Te escuché. Puedes revisar tu respuesta antes de guardar.');};try{rec.start()}catch(e){console.warn(e);toast('No pude iniciar el micrófono. Inténtalo otra vez.');}}
function normalizeSpeechWords(text){return String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zñ0-9\s]/gi,' ').split(/\s+/).filter(Boolean)}
function approximateReadingFeedback(expected,heard){const exp=normalizeSpeechWords(expected),got=normalizeSpeechWords(heard);if(!got.length)return 'No pude reconocer palabras todavía. Inténtalo otra vez.';const counts=new Map();for(const w of exp)counts.set(w,(counts.get(w)||0)+1);let matched=0;for(const w of got){const n=counts.get(w)||0;if(n>0){matched++;counts.set(w,n-1)}}const pct=Math.round(matched/Math.max(1,exp.length)*100);if(pct>=75)return '¡Muy bien! Reconocí gran parte de tu lectura. Puedes volver a leer para ganar seguridad.';if(pct>=45)return 'Te escuché leyendo varias palabras. Intenta otra vez, más despacio y cerca del micrófono.';return 'Te escuché, pero el reconocimiento fue parcial. Lee despacio y vuelve a intentarlo.';}
async function startStudentReading(r){let box=$('#readingSpeechResult');if(!box){box=document.createElement('div');box.id='readingSpeechResult';box.className='speech-result';$('#stage')?.appendChild(box);}box.hidden=false;box.textContent='🎙️ Preparando micrófono…';let ghost=document.querySelector('#readingCapture');if(!ghost){ghost=document.createElement('textarea');ghost.id='readingCapture';ghost.hidden=true;$('#stage')?.appendChild(ghost);}ghost.value='';const button=$('#studentReadBtn')||$('#readAgainMic');await startDictation('#readingCapture',{button,label:'🎙️ Ahora leo yo',continuous:true});const poll=setInterval(()=>{if(activeRecognition){box.textContent=$('#readingCapture').value.trim()?`Te estoy escuchando: “${$('#readingCapture').value.trim()}”`:'🎙️ Te escucho… lee con calma.';}else{clearInterval(poll);const heard=$('#readingCapture').value.trim();box.textContent=approximateReadingFeedback(r.body_text,heard);if(heard){state.progress[r.code]={...(state.progress[r.code]||{}),lastOralReading:heard,lastOralReadingAt:new Date().toISOString()};saveProgress();}}},500);}
