function readingCard(r){const p=state.progress[r.code]||{};return `<article class="reading-card ${p.completed?'done':''}" data-code="${r.code}"><div class="icon">${r.emoji}</div><div><span class="eyebrow">LECTURA ${r.code}</span><h3>${escapeHtml(r.title)}</h3><p>${r.word_count||r.body_text.split(/\s+/).length} palabras · ${r.words.length} palabras focales</p></div><div class="status-dot">${p.completed?'✓':'›'}</div></article>`}
function renderHome(){ $('#readingGrid').innerHTML=state.readings.map(readingCard).join('');document.querySelectorAll('.reading-card').forEach(c=>c.onclick=()=>openReading(c.dataset.code));const done=Object.values(state.progress).filter(p=>p.completed).length;$('#doneCount').textContent=done;$('#globalBar').style.width=`${Math.round(done/Math.max(1,state.readings.length)*100)}%`;const pending=state.events.some(e=>!e.synced);$('#syncLabel').textContent=navigator.onLine?(pending?'Hay avances pendientes de sincronizar':state.binding?.student_id?'Sincronización disponible':'Guardado local · falta vincular este dispositivo'):'Guardado en este dispositivo · sin Internet';}
function showView(id){['studentHome','readerView','teacherView'].forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));}
function openReading(code){state.current=state.readings.find(r=>r.code===code);state.step=state.progress[code]?.lastStep||0;state.answers={};$('#readingCode').textContent='LECTURA '+code;$('#readingTitle').textContent=state.current.title;$('#readingEmoji').textContent=state.current.emoji;showView('readerView');renderReader();}
function renderStepper(){ $('#stepper').innerHTML=steps.map((s,i)=>`<div class="step ${i===state.step?'active':i<state.step?'done':''}">${i+1}. ${s}</div>`).join(''); }
function wordText(w){return typeof w==='string'?w:(w.word||'')}
function wordEmoji(w){return w.emoji||emojiForWord(wordText(w))}
function highlightText(text,words){let out=escapeHtml(text);words.forEach(w=>{const x=wordText(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(`\\b(${x}s?)\\b`,'gi'),'<mark>$1</mark>')});return out}
function makeFindable(r){let text=escapeHtml(r.body_text);r.words.forEach(w=>{const x=wordText(w).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');text=text.replace(new RegExp(`\\b(${x}s?)\\b`,'gi'),m=>`<span class="find-word" data-word="${escapeHtml(wordText(w))}">${m}</span>`)});return text}
function questionHtml(q,i){
  const options=Array.isArray(q.options)&&q.options.length?q.options:null;
  if(options)return `<div class="question" data-q="${i}" data-answer="${escapeHtml(q.answer)}"><span class="eyebrow">${escapeHtml(q.level).toUpperCase()}</span><h3>${escapeHtml(q.prompt)}</h3><div class="options">${options.map(o=>`<button class="option" data-value="${escapeHtml(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="feedback"></div></div>`;
  return `<div class="question" data-q="${i}"><span class="eyebrow">${escapeHtml(q.level).toUpperCase()}</span><h3>${escapeHtml(q.prompt)}</h3><textarea id="openQ${i}" class="big-input" placeholder="Escribe o dicta tu respuesta..."></textarea><div class="audio-row"><button class="primary save-open" data-q="${i}">Guardar respuesta</button><button class="secondary mic-open" data-q="${i}">🎙️ Dictar</button></div><div class="feedback"></div></div>`;
}
function renderReader(){
  const r=state.current;renderStepper();$('#prevBtn').disabled=state.step===0;$('#nextBtn').textContent=state.step===steps.length-1?'Terminar':'Continuar';const stage=$('#stage');
  if(state.step===0){stage.innerHTML=`<div class="prediction-scene"><div class="visual-box">${r.emoji}<br><small>🤔</small></div><div><h2 class="stage-title">Antes de leer</h2><p class="stage-lead">${escapeHtml(r.prediction)}</p><textarea id="predictionInput" class="big-input" placeholder="Puedes escribir una palabra, una idea o contársela al docente...">${escapeHtml(state.progress[r.code]?.prediction||'')}</textarea><div class="audio-row"><button id="savePrediction" class="primary">Guardar mi predicción</button></div></div></div>`;$('#savePrediction').onclick=async()=>{const v=$('#predictionInput').value.trim();if(!v){toast('Escribe o dicta una idea antes de guardar.');return;}state.progress[r.code]={...(state.progress[r.code]||{}),prediction:v};await saveProgress();await logEvent('prediction_saved','prediction',{text:v});toast('Predicción guardada');};}
  if(state.step===1){stage.innerHTML=`<h2 class="stage-title">Leemos el texto completo</h2><div class="reading-scene"><div class="visual-box">${r.emoji}<br>🏔️</div><div><div class="reading-text">${highlightText(r.body_text,r.words)}</div><div class="audio-row"><button id="speakBtn" class="primary">🔊 Escuchar texto</button><button id="stopSpeak" class="secondary">Detener</button></div></div></div>`;$('#speakBtn').onclick=async()=>{speak(r.body_text);await logEvent('audio_played','reading_audio',{source:'speechSynthesis'});};$('#stopSpeak').onclick=()=>speechSynthesis.cancel();}
  if(state.step===2){stage.innerHTML=`<h2 class="stage-title">Trabajamos palabras</h2><p class="stage-lead">Mira, di la palabra y reconoce cómo cambia entre mayúscula y minúscula.</p><div class="word-grid">${r.words.map(w=>`<button class="word-card word-practice" data-word="${escapeHtml(wordText(w))}"><div class="emoji">${wordEmoji(w)}</div><b>${escapeHtml(wordText(w))}</b><div class="case-pair"><span class="case-chip">${escapeHtml((w.display_upper||wordText(w).toUpperCase()))}</span><span>↔</span><span class="case-chip">${escapeHtml((w.display_lower||wordText(w).toLowerCase()))}</span></div></button>`).join('')}</div><h3>Encuéntralas en el texto</h3><div class="reading-text find-text">${makeFindable(r)}</div><p id="findFeedback" class="feedback">Encontradas: 0/${r.words.length}</p>`;let found=new Set();document.querySelectorAll('.word-practice').forEach(el=>el.onclick=async()=>{const w=el.dataset.word;el.classList.add('found');const wordObj=r.words.find(x=>wordText(x)===w);await logEvent('word_image_matched',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null});await logEvent('case_pair_matched',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null})});document.querySelectorAll('.find-word').forEach(el=>el.onclick=async()=>{const w=el.dataset.word;el.classList.add('found');if(!found.has(w)){found.add(w);const wordObj=r.words.find(x=>wordText(x)===w);await logEvent('word_found_in_text',`word:${wordObj?.id||w}`,{word:w,word_id:wordObj?.id||null});$('#findFeedback').textContent=`Encontradas: ${found.size}/${r.words.length}`;if(found.size===r.words.length)toast('¡Encontraste todas las palabras!')}});}
  if(state.step===3){stage.innerHTML=`<h2 class="stage-title">Comprendemos</h2><p class="stage-lead">Puedes volver al texto antes de responder.</p><details><summary>📖 Volver al texto</summary><div class="reading-text">${highlightText(r.body_text,r.words)}</div></details><div id="questions">${r.questions.map((q,i)=>questionHtml(q,i)).join('')}</div>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectOption(b));document.querySelectorAll('.save-open').forEach(b=>b.onclick=()=>saveOpenAnswer(+b.dataset.q));document.querySelectorAll('.mic-open').forEach(b=>b.onclick=()=>startDictation(`#openQ${b.dataset.q}`));}
  if(state.step===4){stage.innerHTML=`<div class="transfer-scene"><div class="visual-box">🏠 ↔ ${r.emoji}</div><div class="transfer-box"><h2 class="stage-title">Lo llevo a mi vida</h2><p class="stage-lead">${escapeHtml(r.transfer)}</p><textarea id="transferInput" class="big-input" placeholder="Escribe, dicta o cuenta tu respuesta...">${escapeHtml(state.progress[r.code]?.transfer||'')}</textarea><div class="audio-row"><button id="transferSave" class="primary">Guardar respuesta</button><button id="micBtn" class="secondary">🎙️ Dictar</button></div></div></div>`;$('#transferSave').onclick=async()=>{const v=$('#transferInput').value.trim();if(!v){toast('Escribe o dicta una respuesta antes de guardar.');return;}state.progress[r.code]={...(state.progress[r.code]||{}),transfer:v};await saveProgress();await logEvent('transfer_answered','transfer',{text:v});toast('Respuesta guardada')};$('#micBtn').onclick=()=>startDictation('#transferInput');}
  if(state.step===5){stage.innerHTML=`<div class="celebrate"><div class="big">📖✨</div><h2>¡Una relectura más!</h2><p class="stage-lead">Vuelve a leer el texto. Esta vez busca las palabras que ya conoces.</p><div class="reading-text">${highlightText(r.body_text,r.words)}</div><div class="audio-row" style="justify-content:center"><button id="rereadBtn" class="primary">🔄 Registrar relectura</button><button id="listenAgain" class="secondary">🔊 Escuchar otra vez</button></div></div>`;$('#rereadBtn').onclick=async()=>{state.progress[r.code]={...(state.progress[r.code]||{}),rereads:(state.progress[r.code]?.rereads||0)+1};await saveProgress();await logEvent('reread_started','reread',{count:state.progress[r.code].rereads});toast('Relectura registrada')};$('#listenAgain').onclick=()=>speak(r.body_text);}
  $('#prevBtn').onclick=()=>{if(state.step>0){state.step--;renderReader()}};$('#nextBtn').onclick=nextStep;
}
async function selectOption(btn){const wrap=btn.closest('.question');if(wrap.dataset.locked)return;wrap.dataset.locked='1';wrap.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');const good=btn.dataset.value===wrap.dataset.answer;btn.classList.add(good?'correct':'incorrect');if(!good){[...wrap.querySelectorAll('.option')].find(x=>x.dataset.value===wrap.dataset.answer)?.classList.add('correct')}wrap.querySelector('.feedback').textContent=good?'✓ Muy bien.':'Revisa la respuesta y vuelve al texto.';const i=+wrap.dataset.q;state.answers[i]=btn.dataset.value;const q=state.current.questions[i];await logEvent('question_answered',`question:${q.id||i+1}`,{question_id:q.id||null,question_prompt:q.prompt,level:q.level,answer:btn.dataset.value,correct:good,open:false});}
async function saveOpenAnswer(i){const v=$(`#openQ${i}`).value.trim();const q=state.current.questions[i];if(!v){toast('Escribe o dicta una respuesta antes de guardar.');return;}state.answers[i]=v;await logEvent('question_answered',`question:${q.id||i+1}`,{question_id:q.id||null,question_prompt:q.prompt,level:q.level,answer:v,open:true,teacher_review:true});document.querySelector(`.question[data-q="${i}"] .feedback`).textContent='✓ Respuesta guardada para revisión.';toast('Respuesta guardada');}
async function nextStep(){const r=state.current;if(state.step<steps.length-1){state.step++;state.progress[r.code]={...(state.progress[r.code]||{}),lastStep:state.step};await saveProgress();renderReader();window.scrollTo({top:0,behavior:'smooth'});}else{state.progress[r.code]={...(state.progress[r.code]||{}),completed:true,completedAt:new Date().toISOString(),lastStep:5};await saveProgress();await logEvent('reading_completed','reading_complete',{reading_code:r.code});renderHome();showView('studentHome');toast('¡Lectura completada!');}}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-PE';u.rate=.82;u.pitch=1;speechSynthesis.speak(u);}
function startDictation(selector){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){toast('El dictado no está disponible en este navegador.');return;}const rec=new SR();rec.lang='es-PE';rec.interimResults=false;rec.onresult=e=>{$(selector).value=e.results[0][0].transcript||'';toast('Dictado recibido')};rec.onerror=()=>toast('No se pudo usar el micrófono.');rec.start();}

